Programming/ruby/rails/pinclone/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/about'

end

Programming/ruby/rails/pinclone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Programming/ruby/rails/pinclone/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

end

Programming/ruby/rails/pinclone/app/helpers/application_helper.rb
module ApplicationHelper
end

Programming/ruby/rails/pinclone/app/helpers/home_helper.rb
module HomeHelper
end

Programming/ruby/rails/pinclone/app/views/home/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <%= link_to 'Pinclone', root_path, class: 'navbar-brand' %>
    </div>
    <!-- Collect the new links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About Me', home_about_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

Programming/ruby/rails/pinclone/app/views/home/about.html.erb
<h1>About Me...</h1>
<p>My name is Craig Waites and I'm building a Pinterest clone</p>

Programming/ruby/rails/pinclone/app/views/home/index.html.erb
<div class="jumbotron">
  <h1>Welcome To My App</h1>
  <p>It's going to be amazing...</p>
  <%= link_to 'About Us', home_about_path, class: 'btn btn-default' %>
  <%= link_to 'Home', root_path, class: 'btn btn-primary' %>
</div>

Programming/ruby/rails/pinclone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinclone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'home/header' %>

<div class="container">
   <%= yield %>
</div>

</body>
</html>